/**
 * Biblioteca Andina - Datos culturales, cuentos, quechua cotidiano y curiosidades.
 * Diseñado para la pestaña 'Explorar' de Yachay Simi: una biblioteca abierta sin bloqueos ni exámenes.
 */

export interface LibraryStory {
  id: string;
  slug: string;
  title: string;
  quechuaTitle: string;
  level: string;
  icon: string;
  description: string;
  tag: string;
}

export interface LibraryItem {
  id: string;
  category: 'cultura' | 'cotidiano' | 'naturaleza' | 'curiosidades';
  subCategory: string;
  qu: string;
  es: string;
  phonetic?: string;
  description: string;
  icon?: string;
  culturalNote?: string;
}

export type CategoryFilter = 'all' | 'historias' | 'cultura' | 'cotidiano' | 'naturaleza' | 'curiosidades' | 'guias';

export const CATEGORY_PILLS: { key: CategoryFilter; label: string; icon: string }[] = [
  { key: 'all',          label: 'Todo',                 icon: '✨' },
  { key: 'historias',    label: 'Cuentos del Ayllu',    icon: '📖' },
  { key: 'cultura',      label: 'Cultura & Tradición',  icon: '🏔️' },
  { key: 'cotidiano',    label: 'Quechua Cotidiano',    icon: '💬' },
  { key: 'naturaleza',   label: 'Mundo Andino',         icon: '🦙' },
  { key: 'curiosidades', label: 'Secretos del Idioma',  icon: '💡' },
  { key: 'guias',        label: 'Guías Lingüísticas',   icon: '📜' },
];

export const LIBRARY_STORIES: LibraryStory[] = [
  {
    id: 'story-1',
    slug: 'el-zorro-y-el-condor',
    title: 'El Zorro y el Cóndor',
    quechuaTitle: 'Atoqmantawan Kunturmantawan',
    level: 'Principiante • Tradición',
    icon: '🦊🦅',
    description: 'Acompaña al zorro en su mítico ascenso al Hanan Pacha para traer los alimentos sagrados a la tierra.',
    tag: 'Mito Andino',
  },
  {
    id: 'story-2',
    slug: 'manco-capac',
    title: 'Manco Cápac y Mama Ocllo',
    quechuaTitle: 'Manco Cápac Mama Ocllowan',
    level: 'Intermedio • Historia',
    icon: '☀️👑',
    description: 'La leyenda de cómo los hijos del Sol emergieron del lago Titicaca para fundar el Tawantinsuyu.',
    tag: 'Origen Sagrado',
  },
  {
    id: 'story-3',
    slug: 'sumaq-kawsay',
    title: 'El Buen Vivir (Sumaq Kawsay)',
    quechuaTitle: 'Sumaq Kawsaymanta',
    level: 'Sabiduría Ancestral',
    icon: '🌿🏔️',
    description: 'Descubre los principios de armonía con la Pachamama y el código moral incaico para vivir en plenitud.',
    tag: 'Filosofía',
  },
  {
    id: 'story-4',
    slug: 'numeros',
    title: 'Contando con Yachi',
    quechuaTitle: 'Yupaykuna Yachay',
    level: 'Básico • Diálogo',
    icon: '🔢✨',
    description: 'Aprende los números sagrados del 1 al 10 en Quechua interactuando con tu amigo Yachi.',
    tag: 'Números',
  },
  {
    id: 'story-5',
    slug: 'abecedario',
    title: 'Una Casa Quechua',
    quechuaTitle: 'Wasiy Yachay',
    level: 'Básico • Entorno',
    icon: '🏡⛰️',
    description: 'Conoce los nombres de las cosas del hogar andino y los términos fundamentales de convivencia.',
    tag: 'Hogar',
  },
  {
    id: 'story-6',
    slug: 'palabras',
    title: 'Un Saludo con Yachi',
    quechuaTitle: 'Napaykuna Yachiwan',
    level: 'Básico • Diálogo',
    icon: '💬👋',
    description: 'Practica saludos respetuosos según la hora del día y fórmulas tradicionales de cortesía.',
    tag: 'Cortesía',
  },
];

export const LIBRARY_ITEMS: LibraryItem[] = [
  // ─── CULTURA & TRADICIÓN (Gastronomía, Vestimenta, Música, Sagrado) ───
  {
    id: 'cul-1',
    category: 'cultura',
    subCategory: 'Gastronomía Ancestral',
    qu: 'Pachamanka',
    es: 'Comida cocida bajo tierra',
    phonetic: 'pah-chah-mahn-kah',
    description: 'Banquete milenario cocinado bajo tierra con piedras volcánicas ardientes en honor a la Pachamama.',
    culturalNote: 'Simboliza el vientre fértil de la Madre Tierra que alimenta y une a la comunidad.',
    icon: '🥘',
  },
  {
    id: 'cul-2',
    category: 'cultura',
    subCategory: 'Gastronomía Ancestral',
    qu: 'Kankacho',
    es: 'Asado de cordero andino',
    phonetic: 'kahn-kah-choh',
    description: 'Tradicional asado de cordero del altiplano, macerado con ají panca, ajo y chicha de jora.',
    culturalNote: 'Plato emblemático de las festividades comunales en Puno y Cusco.',
    icon: '🍖',
  },
  {
    id: 'cul-3',
    category: 'cultura',
    subCategory: 'Gastronomía Ancestral',
    qu: 'Kinwa',
    es: 'Quinua sagrada',
    phonetic: 'keen-wah',
    description: 'Grano de oro de los incas con altísimo valor nutricional, resistente a las heladas de la puna.',
    culturalNote: 'Llamada ancestralmente Chisaya Mama (la madre de todos los granos).',
    icon: '🌾',
  },
  {
    id: 'cul-4',
    category: 'cultura',
    subCategory: 'Gastronomía Ancestral',
    qu: 'Sara',
    es: 'Maíz sagrado',
    phonetic: 'sah-rah',
    description: 'Base fundamental de la alimentación andina y de la sagrada chicha de jora (aqha).',
    culturalNote: 'Asociado al Sol y a la fertilidad en la cosmovisión incaica.',
    icon: '🌽',
  },
  {
    id: 'cul-5',
    category: 'cultura',
    subCategory: 'Vestimenta Tradicional',
    qu: 'Ch\'ullu',
    es: 'Gorro andino con orejeras',
    phonetic: 'chool-yoo',
    description: 'Gorro tejido en fibra de alpaca con orejeras protectoras contra los vientos de las altas cumbres.',
    culturalNote: 'La iconografía tejida (pallay) comunica la comunidad de origen y el estatus social.',
    icon: '🧶',
  },
  {
    id: 'cul-6',
    category: 'cultura',
    subCategory: 'Vestimenta Tradicional',
    qu: 'Lliklla',
    es: 'Manta tradicional de hombro',
    phonetic: 'yeek-lyah',
    description: 'Manta rectangular tejida a mano que las mujeres llevan sobre la espalda para abrigo y transporte.',
    culturalNote: 'Usada para cargar a los bebés (wawas) en estrecho contacto con el calor materno.',
    icon: '🧣',
  },
  {
    id: 'cul-7',
    category: 'cultura',
    subCategory: 'Vestimenta Tradicional',
    qu: 'Chumpi',
    es: 'Faja tejida con memoria',
    phonetic: 'choom-pee',
    description: 'Faja ceñidora con figuras geométricas sagradas que narran mitos e historias comunitarias.',
    culturalNote: 'Funciona como un documento textil que preserva la memoria viva del ayllu.',
    icon: '🎀',
  },
  {
    id: 'cul-8',
    category: 'cultura',
    subCategory: 'Música & Danzas',
    qu: 'Charango',
    es: 'Instrumento de cuerda andino',
    phonetic: 'chah-rahn-goh',
    description: 'Pequeño cordófono de diez cuerdas dobles de sonido brillante y agudo, nacido en los Andes.',
    culturalNote: 'Expresa tanto la ternura melancólica del huayno como la alegría de las cosechas.',
    icon: '🪕',
  },
  {
    id: 'cul-9',
    category: 'cultura',
    subCategory: 'Música & Danzas',
    qu: 'Qina',
    es: 'Flauta andina milenaria',
    phonetic: 'kee-nah',
    description: 'Flauta tradicional de caña o madera de sonido dulce y profundo, soplada verticalmente.',
    culturalNote: 'Uno de los instrumentos aerófonos más antiguos de América Latina.',
    icon: '🎶',
  },
  {
    id: 'cul-10',
    category: 'cultura',
    subCategory: 'Música & Danzas',
    qu: 'Siku',
    es: 'Zampoña / Flauta de pan',
    phonetic: 'see-koo',
    description: 'Instrumento de cañas ordenadas en dos filas complementarias tocadas en pareja.',
    culturalNote: 'Encarne vivo del Ayni: dos sikuris deben turnarse para formar la melodía completa.',
    icon: '🪈',
  },
  {
    id: 'cul-11',
    category: 'cultura',
    subCategory: 'Lugares Sagrados & Principios',
    qu: 'Apu',
    es: 'Montaña tutelar protectora',
    phonetic: 'ah-poo',
    description: 'Nevados y montañas sagradas que protegen a las comunidades, controlan el clima y nutren los valles.',
    culturalNote: 'Se les rinde ofrendas de respeto (haywarikuy) pidiendo bienestar y buenas cosechas.',
    icon: '🏔️',
  },
  {
    id: 'cul-12',
    category: 'cultura',
    subCategory: 'Lugares Sagrados & Principios',
    qu: 'Ayni',
    es: 'Reciprocidad solidaria',
    phonetic: 'ahy-nee',
    description: 'Principio fundamental de vida andina: "Hoy por ti, mañana por mí". Ayuda mutua comunitaria.',
    culturalNote: 'Pilar ético que aseguró la autosuficiencia y fortaleza del Tawantinsuyu.',
    icon: '🤝',
  },
  {
    id: 'cul-13',
    category: 'cultura',
    subCategory: 'Lugares Sagrados & Principios',
    qu: 'Minka',
    es: 'Trabajo colectivo comunitario',
    phonetic: 'meen-kah',
    description: 'Labor comunitaria voluntaria y festiva para el beneficio común (caminos, puentes, siembra).',
    culturalNote: 'Se realiza con música, comida compartida y celebración colectiva.',
    icon: '🌾',
  },

  // ─── QUECHUA COTIDIANO (Saludos, Cortesía, Código Moral) ───
  {
    id: 'cot-1',
    category: 'cotidiano',
    subCategory: 'Saludos y Despedidas',
    qu: "Allin p'unchaw",
    es: 'Buenos días',
    phonetic: 'ah-yeen poon-chahw',
    description: 'Saludo matutino para desear una jornada llena de luz y energía positiva.',
    culturalNote: 'P\'unchaw hace referencia al sol resplandeciente en el cielo.',
    icon: '🌅',
  },
  {
    id: 'cot-2',
    category: 'cotidiano',
    subCategory: 'Saludos y Despedidas',
    qu: 'Allin suka',
    es: 'Buenas tardes',
    phonetic: 'ah-yeen soo-kah',
    description: 'Saludo cordial empleado desde el mediodía hasta el atardecer.',
    culturalNote: 'Suka marca el declive sereno del sol hacia las montañas.',
    icon: '☀️',
  },
  {
    id: 'cot-3',
    category: 'cotidiano',
    subCategory: 'Saludos y Despedidas',
    qu: 'Allin tuta',
    es: 'Buenas noches',
    phonetic: 'ah-yeen too-tah',
    description: 'Saludo y despedida nocturna para invocar un sueño reparador y en paz.',
    culturalNote: 'Tuta designa la noche protegida por la luna (Killa) y las estrellas.',
    icon: '🌙',
  },
  {
    id: 'cot-4',
    category: 'cotidiano',
    subCategory: 'Saludos y Despedidas',
    qu: 'Tupananchiskama',
    es: 'Hasta que volvamos a encontrarnos',
    phonetic: 'too-pah-nahn-chees-kah-mah',
    description: 'Despedida tradicional: en el mundo andino nunca hay un adiós definitivo, siempre hay reencuentro.',
    culturalNote: 'Expresa la certeza de que el camino de la vida nos volverá a reunir.',
    icon: '👋',
  },
  {
    id: 'cot-5',
    category: 'cotidiano',
    subCategory: 'Saludos y Despedidas',
    qu: 'Paqarinkama',
    es: 'Hasta mañana',
    phonetic: 'pah-qah-reen-kah-mah',
    description: 'Despedida esperanzadora hacia el día siguiente.',
    culturalNote: 'El sufijo -kama denota el límite temporal ("hasta").',
    icon: '🌤️',
  },
  {
    id: 'cot-6',
    category: 'cotidiano',
    subCategory: 'Cortesía & Afecto',
    qu: 'Allillanchu?',
    es: '¿Cómo estás? / ¿Estás en paz?',
    phonetic: 'ah-yeel-yahn-choo',
    description: 'La pregunta más común de cortesía andina al iniciar cualquier conversación.',
    culturalNote: 'Pregunta si uno se encuentra en armonía interior y con su entorno.',
    icon: '❓',
  },
  {
    id: 'cot-7',
    category: 'cotidiano',
    subCategory: 'Cortesía & Afecto',
    qu: 'Allillanmi',
    es: 'Estoy bien / Todo en armonía',
    phonetic: 'ah-yeel-yahn-mee',
    description: 'Respuesta formal y sincera al saludo Allillanchu.',
    culturalNote: 'El sufijo -mi aporta certeza y testimonio directo de bienestar.',
    icon: '✨',
  },
  {
    id: 'cot-8',
    category: 'cotidiano',
    subCategory: 'Cortesía & Afecto',
    qu: 'Añay',
    es: 'Muchas gracias / Te agradezco',
    phonetic: 'ah-nyahy',
    description: 'Fórmula de gratitud profunda y afectuosa nacida del corazón.',
    culturalNote: 'También se emplea "Yupaychani" para expresar reverencia y honra a quien ayudó.',
    icon: '🙏',
  },
  {
    id: 'cot-9',
    category: 'cotidiano',
    subCategory: 'Cortesía & Afecto',
    qu: 'Munakuyki',
    es: 'Te quiero / Te amo',
    phonetic: 'moo-nah-kooy-kee',
    description: 'Declaración pura de amor y cariño sincero hacia familiares, amigos o la pareja.',
    culturalNote: 'Munay une el querer, desear y amar con ternura y respeto.',
    icon: '💖',
  },
  {
    id: 'cot-10',
    category: 'cotidiano',
    subCategory: 'Cortesía & Afecto',
    qu: 'Sonqoy',
    es: 'Mi corazón / Cariño mío',
    phonetic: 'sohn-qohy',
    description: 'Término de máximo afecto para seres queridos e hijos.',
    culturalNote: 'En el pensamiento quechua, el corazón (sonqo) es el centro del entendimiento.',
    icon: '❤️',
  },
  {
    id: 'cot-11',
    category: 'cotidiano',
    subCategory: 'Código Moral Incaico',
    qu: 'Ama Suwa',
    es: 'No seas ladrón',
    phonetic: 'ah-mah soo-wah',
    description: 'Primer principio del código ético inca: respeta el esfuerzo y los bienes de tu prójimo.',
    culturalNote: 'En las comunidades incas no hacían falta cerrojos; el respeto mutuo era ley sagrada.',
    icon: '🛡️',
  },
  {
    id: 'cot-12',
    category: 'cotidiano',
    subCategory: 'Código Moral Incaico',
    qu: 'Ama Llulla',
    es: 'No seas mentiroso',
    phonetic: 'ah-mah lyool-lyah',
    description: 'Segundo principio: mantén siempre la verdad y honra la palabra empeñada.',
    culturalNote: 'La palabra de un quechua valía más que cualquier pacto escrito.',
    icon: '🕊️',
  },
  {
    id: 'cot-13',
    category: 'cotidiano',
    subCategory: 'Código Moral Incaico',
    qu: 'Ama Qilla',
    es: 'No seas perezoso',
    phonetic: 'ah-mah qeel-lyah',
    description: 'Tercer principio: trabaja con dedicación, esmero y alegría para el bienestar colectivo.',
    culturalNote: 'El trabajo en el campo era vivido como una fiesta alegre y creadora de vida.',
    icon: '⚡',
  },

  // ─── MUNDO ANDINO (Fauna Sagrada, Flora Medicinal) ───
  {
    id: 'nat-1',
    category: 'naturaleza',
    subCategory: 'Fauna Sagrada',
    qu: 'Kuntur',
    es: 'Cóndor andino',
    phonetic: 'koon-toor',
    description: 'Rey de las alturas andinas y mensajero del Hanan Pacha (mundo celestial).',
    culturalNote: 'Vuela entre los nevados uniendo a los hombres con el Sol y los Apus.',
    icon: '🦅',
  },
  {
    id: 'nat-2',
    category: 'naturaleza',
    subCategory: 'Fauna Sagrada',
    qu: 'Puma',
    es: 'Puma andino',
    phonetic: 'poo-mah',
    description: 'Guardián del Kay Pacha (mundo terrenal), símbolo de fuerza, sabiduría y liderazgo.',
    culturalNote: 'La ciudad imperial del Cusco fue diseñada con la forma anatómica de un gran puma.',
    icon: '🐾',
  },
  {
    id: 'nat-3',
    category: 'naturaleza',
    subCategory: 'Fauna Sagrada',
    qu: 'Amaru',
    es: 'Serpiente sagrada',
    phonetic: 'ah-mah-roo',
    description: 'Protectora del Uku Pacha (mundo subterráneo e interior), símbolo de la sabiduría de las aguas.',
    culturalNote: 'Asociada a los ríos subterráneos y al rayo que fecunda la tierra.',
    icon: '🐍',
  },
  {
    id: 'nat-4',
    category: 'naturaleza',
    subCategory: 'Fauna Sagrada',
    qu: 'Wik\'uña',
    es: 'Vicuña silvestre',
    phonetic: 'wee-koon-yah',
    description: 'Camélido silvestre de las altas mesetas que produce una de las fibras más finas del mundo.',
    culturalNote: 'Durante el incanato se esquilaba en la ceremonia del Chaccu sin lastimar al animal.',
    icon: '🦙',
  },
  {
    id: 'nat-5',
    category: 'naturaleza',
    subCategory: 'Flora Medicinal & Sagrada',
    qu: 'Kuka',
    es: 'Hoja de coca sagrada',
    phonetic: 'koo-kah',
    description: 'Hoja milenaria usada en el akulliku para aliviar la fatiga de la altura y en pagos a la tierra.',
    culturalNote: 'Considerada sagrada por permitir la comunicación espiritual con la Pachamama.',
    icon: '🍃',
  },
  {
    id: 'nat-6',
    category: 'naturaleza',
    subCategory: 'Flora Medicinal & Sagrada',
    qu: 'Muña',
    es: 'Hierba aromática de altura',
    phonetic: 'moo-nyah',
    description: 'Arbusto aromático de valles interandinos con extraordinarias virtudes digestivas.',
    culturalNote: 'Se toma caliente como infusión para templar el cuerpo y aliviar el mal de altura.',
    icon: '🌿',
  },
  {
    id: 'nat-7',
    category: 'naturaleza',
    subCategory: 'Flora Medicinal & Sagrada',
    qu: 'Chachakuma',
    es: 'Planta medicinal de puna',
    phonetic: 'chah-chah-koo-mah',
    description: 'Planta que crece sobre los 3,800 msnm, excelente contra resfriados, tos y afecciones respiratorias.',
    culturalNote: 'Utilizada ancestralmente por los pastores de altura en infusiones y baños de vapor.',
    icon: '🌱',
  },
  {
    id: 'nat-8',
    category: 'naturaleza',
    subCategory: 'Flora Medicinal & Sagrada',
    qu: 'Qantu',
    es: 'Flor de la Cantuta',
    phonetic: 'qahn-too',
    description: 'Flor acampanada sagrada de los incas de vivos tonos rojos y amarillos, flor emblemática andina.',
    culturalNote: 'Consagrada al dios Sol (Inti) y entregada como corona a los jóvenes que culminaban su rito de paso.',
    icon: '🌺',
  },

  // ─── CURIOSIDADES & SECRETOS DEL IDIOMA ───
  {
    id: 'cur-1',
    category: 'curiosidades',
    subCategory: 'Fonética Achahala',
    qu: 'Achahala (A - I - U)',
    es: 'El sistema trivocálico',
    phonetic: 'ah-chah-hah-lah',
    description: 'En el Quechua originario solo existen tres vocales fonémicas: A, I y U. Las letras E y O son alófonos producidos al estar cerca de la posvelar Q.',
    culturalNote: 'Por eso en escritura normalizada se escribe "Qosqo" o "Quri" manteniendo su raíz pura.',
    icon: '🔤',
  },
  {
    id: 'cur-2',
    category: 'curiosidades',
    subCategory: 'Estructura Gramatical',
    qu: 'Simi T\'aqakuna',
    es: 'Lengua Aglutinante',
    phonetic: 'see-mee tah-qah-koo-nah',
    description: 'No requiere preposiciones aisladas. Une sufijos a una raíz: Wasi (casa) ➡️ Wasi-y-kuna-pi = "En mis casas".',
    culturalNote: 'Permite condensar una frase entera dentro de una sola palabra con armonía rítmica.',
    icon: '🧩',
  },
  {
    id: 'cur-3',
    category: 'curiosidades',
    subCategory: 'Cosmovisión Social',
    qu: 'Ñoqanchik vs Ñoqayku',
    es: 'La dualidad del "Nosotros"',
    phonetic: 'nyoh-qahn-cheek / nyoh-qahy-koo',
    description: 'Existe un "Nosotros Inclusivo" (Ñoqanchik: tú y yo juntos) y un "Nosotros Exclusivo" (Ñoqayku: nosotros, pero tú no).',
    culturalNote: 'Una precisión social y de empatía ausente en la mayoría de lenguas occidentales.',
    icon: '👥',
  },
  {
    id: 'cur-4',
    category: 'curiosidades',
    subCategory: 'Afecto Lingüístico',
    qu: 'Sufijo -cha',
    es: 'El diminutivo del cariño',
    phonetic: 'chah',
    description: 'Agregar "-cha" convierte cualquier término en ternura: Urpi (paloma) ➡️ Urpicha (palomita querida); Allqo (perro) ➡️ Allqocha (perrito tierno).',
    culturalNote: 'Demuestra el carácter profundamente cariñoso y respetuoso de la cultura quechua.',
    icon: '💝',
  },
];
